apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster-dep
spec:
  template:
    spec:
      containers:
        - name: broadcaster
          env:
            - name: EXTERNAL_WEBHOOK_URL
              value: ""
